on:
  push:
    branches:
      - master 





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing 1'
        run: pwd  
    
      - uses: action/checkout@v3
      - name: 'show folder'
        run: ls -a
      - name: 'login to the docker'
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.DOCKERPASSWORD }}
      - name: 'building image'
        run: docker build -t ${{ secrets.USERNAME }}/firstimage .
      - name: 'push docker image'
        run: docker push ${{ secrets.USERNAME }}/firstimage
    